### ISSUE TITLE
Support .gif encoding

### ISSUE THREAD

**Issue by adrianleb** [ethblockart/backlog#4]
Support outputting .gif files when minting BlockArts from animated BlockStyles

**Comment by gre** [comment]
I would be happy to help on a spec on this. idea is to challenge the spec against different implementations too.

Here are some quick ideas:

### time as a prop

Ideally, the BlockStyle would have to take either a `time` value or a `frame`. I would go for the `time` in seconds personally because it makes you free to chose the framerate then as well as making it compatible with the general /canvas experience (time starting at 0)

### onDraw for BlockStyle to tell when it's ready

Then, I think you can send a `onDraw` callback to the underlying BlockStyle so it can pings back the upper level that the frame is ready. That allows block style to be async.

### BlockStyles to express their constraints?

When we talk about .gif, usually we also want to "loop" it. That needs the BlockStyles to express when is it looping (if it is looping).
The spec have to decide if it's allowed and what are the limits (in term of max time for instance).

on my end, when i was doing this, i would usually define a `startTime`, `endTime`, `frameRate` for the renderer to then run it by injecting a time.

> You can see a PoC of this in https://github.com/gre/shaderday.com/blob/master/pages/export/%5Bday%5D/index.js (specific to gl-react)

### on tech side

you can use library like https://github.com/mattdesl/gifenc but it's not always easy to get it right regarding the palette / dithering.

Is video considered?

**Comment by adrianleb** [comment]
Closing this for now given our focus on live canvas first, we can revisit it later!

**Comment by gre** [comment]
Yeah gif is actually complex because it's size limit and the 256 palette limitations which easily can do flickering
